//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "portfolio_snapshots")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub captured_on: Date,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))")]
    pub invested_eur: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))")]
    pub current_value_eur: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))")]
    pub pnl_eur: Decimal,
    pub position_count: i16,
    pub quote_error: bool,
    pub portfolio_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::portfolios::Entity",
        from = "Column::PortfolioId",
        to = "super::portfolios::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Portfolios,
}

impl Related<super::portfolios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Portfolios.def()
    }
}
