//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "watchlist_items")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub position: i64,
    #[sea_orm(unique_key = "uniq_watchlist_items_watchlist_instrument")]
    pub watchlist_id: i64,
    pub watchlist_section_id: i64,
    #[sea_orm(unique_key = "uniq_watchlist_items_watchlist_instrument")]
    pub instrument_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::instruments::Entity",
        from = "Column::InstrumentId",
        to = "super::instruments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Instruments,
    #[sea_orm(
        belongs_to = "super::watchlist_sections::Entity",
        from = "Column::WatchlistSectionId",
        to = "super::watchlist_sections::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WatchlistSections,
    #[sea_orm(
        belongs_to = "super::watchlists::Entity",
        from = "Column::WatchlistId",
        to = "super::watchlists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Watchlists,
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instruments.def()
    }
}

impl Related<super::watchlist_sections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchlistSections.def()
    }
}

impl Related<super::watchlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watchlists.def()
    }
}
