//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "watchlist_sections")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub position: i64,
    pub is_default: bool,
    pub watchlist_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::watchlist_items::Entity")]
    WatchlistItems,
    #[sea_orm(
        belongs_to = "super::watchlists::Entity",
        from = "Column::WatchlistId",
        to = "super::watchlists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Watchlists,
}

impl Related<super::watchlist_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchlistItems.def()
    }
}

impl Related<super::watchlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watchlists.def()
    }
}
