// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What adding a ticker did; failures are [`Error::Validation`] instead.
 */
export type AddWatchlistItemStatus = "added" | "moved" | "already_present";
