// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddWatchlistItemStatus } from "./AddWatchlistItemStatus";

export type AddWatchlistItemResponse = { status: AddWatchlistItemStatus, };
