// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartPointDto = { date: string, close: number, open: number | null, high: number | null, low: number | null, volume: number | null, };
