// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatePositionLine } from "./CreatePositionLine";

/**
 * Body of `POST /api/portfolios/{id}/positions`: a ticker plus its buy lots.
 */
export type CreatePosition = { symbol: string, lines: Array<CreatePositionLine>, };
