// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardLine = { transaction_id: number, executed_at: string, original_quantity: number, remaining_quantity: number, unit_price: number, invested: number, current_value: number, pnl: number, pnl_pct: number, };
