// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardInstrument } from "./DashboardInstrument";
import type { DashboardLine } from "./DashboardLine";

export type DashboardPositionKpis = { position_id: number, instrument: DashboardInstrument, quantity: number, avg_cost: number, invested: number, current_value: number, pnl: number, pnl_pct: number, daily_change: number, daily_change_pct: number, currency: string, fx_rate: number, invested_eur: number, current_value_eur: number, pnl_eur: number, daily_change_eur: number, realized_pnl_eur: number, price: number, previous_close: number, realized_pnl: number, lines: Array<DashboardLine>, };
