// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardInstrument = { id: number, symbol: string, name: string, currency: string, exchange: string | null, logo_url: string | null, };
