// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardPortfolioKpis } from "./DashboardPortfolioKpis";
import type { DashboardPortfolioSummary } from "./DashboardPortfolioSummary";

export type DashboardActive = { portfolio: DashboardPortfolioSummary, kpis: DashboardPortfolioKpis, last_updated: string, quote_error: string | null, };
