// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardActive } from "./DashboardActive";
import type { PortfolioDto } from "./PortfolioDto";

export type DashboardResponse = { portfolios: Array<PortfolioDto>, active: DashboardActive | null, };
