// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardPositionKpis } from "./DashboardPositionKpis";

export type DashboardPortfolioKpis = { total_invested: number, current_value: number, pnl: number, pnl_pct: number, daily_change: number, daily_change_pct: number, display_currency: string, positions: Array<DashboardPositionKpis>, };
