// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldValidationError } from "./FieldValidationError";

/**
 * Loco `ErrorDetail` as returned by `JsonValidateWithMessage` and
 * `Error::Validation` / `Error::CustomError`.
 */
export type ErrorDetailDto = { error: string | null, description: string | null, errors: { [key in string]: Array<FieldValidationError> } | null, };
