// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Loco field error (`ErrorDetail.errors[field][i]`).
 */
export type FieldValidationError = { code: string, message: string | null, params: Record<string, unknown>, };
