// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Portfolio value on one day (`YYYY-MM-DD`).
 */
export type HistoryPointDto = { date: string, value_eur: number, invested_eur: number, pnl_eur: number, };
