// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One instrument, merged across portfolios.
 */
export type InstrumentAllocation = { symbol: string, name: string, currency: string, 
/**
 * Lowercase quote type (`equity`, `etf`, ...); `stock` when unknown.
 */
asset_type: string, value_eur: number, invested_eur: number, pnl_eur: number, pnl_pct: number, percent: number, };
