// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortfolioDto = { id: number, user_id: number, name: string, is_default: boolean, created_at: string, updated_at: string, };
