// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PortfolioAllocation = { portfolio_id: number, name: string, value_eur: number, percent: number, };
