// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live tick forwarded on `GET /api/stream` (crate
 * `finance_query::streaming::PriceUpdate` mapped onto a stable JSON contract).
 *
 * Field names match the Yahoo camelCase payload so the SPA parser
 * stays the same (`changePercent`, `openPrice`, …).
 */
export type PriceTickDto = { id: string, price: number, change: number, changePercent: number, dayHigh: number | null, dayLow: number | null, dayVolume: number | null, openPrice: number | null, previousClose: number | null, shortName: string | null, currency: string | null, exchange: string | null, quoteType: string | null, marketHours: string | null, 
/**
 * Unix milliseconds (crate `PriceUpdate.time`).
 */
time: number | null, };
