// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuoteDto } from "./QuoteDto";

/**
 * Envelope for `GET /api/quotes`.
 */
export type QuotesResponse = { quotes: { [key in string]: QuoteDto }, fetched_at: string, };
