// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote fields the SPA needs (watchlist, dashboard, ticker). Stable contract:
 * crate `Quote` types are mapped here and never leaked to JSON.
 */
export type QuoteDto = { symbol: string, name: string | null, exchange: string | null, quote_type: string | null, currency: string | null, regular_market_price: number | null, regular_market_change: number | null, regular_market_change_percent: number | null, regular_market_previous_close: number | null, logo_url: string | null, };
