// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One close point for `GET /api/watchlists/history`.
 *
 * `t` is unix milliseconds; `v` is the close price.
 */
export type SparkPointDto = { t: number, v: number, };
