// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstrumentAllocation } from "./InstrumentAllocation";

/**
 * Best and worst instruments by P&L percentage (at most 5 each).
 */
export type StatisticsPerformance = { top_gainers: Array<InstrumentAllocation>, top_losers: Array<InstrumentAllocation>, };
