// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatisticsTotals = { invested_eur: number, current_value_eur: number, pnl_eur: number, pnl_pct: number, daily_change_eur: number, daily_change_pct: number, position_count: number, instrument_count: number, portfolio_count: number, };
