// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrencyAllocation } from "./CurrencyAllocation";
import type { InstrumentAllocation } from "./InstrumentAllocation";
import type { PortfolioAllocation } from "./PortfolioAllocation";
import type { TypeAllocation } from "./TypeAllocation";

export type StatisticsAllocations = { by_instrument: Array<InstrumentAllocation>, by_currency: Array<CurrencyAllocation>, by_type: Array<TypeAllocation>, 
/**
 * Only filled for the `all` scope.
 */
by_portfolio: Array<PortfolioAllocation>, };
