// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the statistics cover: every portfolio of the user, or a single one.
 */
export type StatisticsScope = { "type": "all" } | { "type": "portfolio", id: number, name: string, };
