// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryPointDto } from "./HistoryPointDto";
import type { PortfolioDto } from "./PortfolioDto";
import type { StatisticsAllocations } from "./StatisticsAllocations";
import type { StatisticsPerformance } from "./StatisticsPerformance";
import type { StatisticsScope } from "./StatisticsScope";
import type { StatisticsTotals } from "./StatisticsTotals";

export type StatisticsResponse = { portfolios: Array<PortfolioDto>, scope: StatisticsScope, totals: StatisticsTotals, allocations: StatisticsAllocations, performance: StatisticsPerformance, history: Array<HistoryPointDto>, generated_at: string, quote_error: string | null, };
