// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartPointDto } from "./ChartPointDto";

export type SymbolChartResponse = { symbol: string, range: string, points: Array<ChartPointDto>, };
