// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolChartDto } from "./SymbolChartDto";
import type { SymbolNewsItemDto } from "./SymbolNewsItemDto";
import type { SymbolQuoteDto } from "./SymbolQuoteDto";
import type { SymbolRecommendationDto } from "./SymbolRecommendationDto";

export type SymbolPageResponse = { symbol: string, quote: SymbolQuoteDto | null, quote_error: string | null, chart: SymbolChartDto, news: Array<SymbolNewsItemDto>, recommendations: Array<SymbolRecommendationDto>, available_ranges: Array<string>, };
