// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One symbol hit returned by `GET /api/symbol-search`.
 *
 * Field names match the payload so the existing React `GlobalSearch` can consume this endpoint unchanged.
 */
export type SymbolSearchResult = { symbol: string, name: string | null, exchange: string | null, type: string | null, logo_url: string | null, };
