// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SymbolNewsItemDto = { title: string, link: string, source: string, image: string | null, time: string, };
