// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Side of a transaction, stored as `buy` / `sell` (guarded by a CHECK constraint).
 */
export type TransactionKind = "buy" | "sell";
