// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionKind } from "./TransactionKind";

export type TransactionDto = { id: number, kind: TransactionKind, quantity: number, unit_price: number, executed_at: string, notes: string | null, position_id: number, };
