// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionKind } from "./TransactionKind";

/**
 * Body of `POST /api/positions/{id}/transactions` and `PUT /api/transactions/{id}`.
 *
 * Amounts accept a JSON number or a decimal string and are never rounded
 * through `f64`.
 */
export type UpsertTransaction = { kind: TransactionKind, quantity: number, unit_price: number, executed_at: string, notes: string | null, };
