// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchlistSummaryDto = { id: number, name: string, default_section_id: number | null, };
