// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistItemDto } from "./WatchlistItemDto";

export type WatchlistSectionDto = { id: number, name: string, position: number, is_default: boolean, items: Array<WatchlistItemDto>, };
