// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistSummaryDto } from "./WatchlistSummaryDto";

export type WatchlistSummaryResponse = { data: Array<WatchlistSummaryDto>, };
