// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistDto } from "./WatchlistDto";
import type { WatchlistLimitsDto } from "./WatchlistLimitsDto";
import type { WatchlistPositionDto } from "./WatchlistPositionDto";

export type WatchlistPageResponse = { watchlists: Array<WatchlistDto>, active_watchlist_id: number | null, positions: { [key in string]: WatchlistPositionDto }, limits: WatchlistLimitsDto, };
