// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Average cost of open lots for a ticker.
 */
export type WatchlistPositionDto = { avg_price: number, quantity: number, currency: string | null, };
