// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SparkPointDto } from "./SparkPointDto";

export type WatchlistHistoryResponse = { data: { [key in string]: Array<SparkPointDto> }, };
