// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchlistInstrumentDto } from "./WatchlistInstrumentDto";

export type WatchlistItemDto = { id: number, section_id: number, position: number, instrument: WatchlistInstrumentDto, };
