// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchlistInstrumentDto = { id: number, symbol: string, name: string, exchange: string | null, quote_type: string | null, currency: string, logo_url: string | null, };
